tf-coreml/tf-coreml

README.md

This PR: 
Add `pip install ` option for the package.

Readme installation documentation update

---

tfcoreml/_ops_to_layers.py

Skips the PlaceholderWithDefault op (Issue #82)

Skip placeholder default op

---

tfcoreml/optimizations/_optimize.py

Typo fix in optimize.py file

---

tfcoreml/_tf_coreml_converter.py

This PR fixes the bug where the probability label output is not renamed correctly, causing conversion calls with non-`None` class_labels to fail.

[Issue 85] Fix classLabel bug

---

README.md
examples/inception_v1_preprocessing_steps.ipynb
tfcoreml/_layers.py
tfcoreml/_ops_to_layers.py
tfcoreml/_shape_sensitive_layers.py

- minimum, exp, floormod ops added
- fixes in some other ops

Minimum, exp ops and fixes

---

tests/test_tf_converter.py
tfcoreml/_layers.py

This PR adds support for dilated depthwise 2D convolution and a small test.

Add support for dilated depthwise conv2d

---

setup.py

Planning to update the pip version to 0.1.1 as a bunch of fixes have gone in since the first release.

Minor update to 0.1.1

---

tfcoreml/_interpret_shapes.py
tfcoreml/_layers.py

Handle the cases when neg and strided_slice op can get constant inputs

---

tfcoreml/optimizations/_optimize.py

Convert argument to byte in mergefromstring call

---

tfcoreml/_interpret_shapes.py
tfcoreml/_layers.py
tfcoreml/_ops_to_layers.py
tfcoreml/_shape_sensitive_layers.py
tfcoreml/_tf_coreml_converter.py
tfcoreml/optimizations/_optimize.py
tfcoreml/optimizations/_optimize_nn_spec.py

- add optimizations for removing identity layer and fusing load constant and mul/add layers
- Add more cases for handling reshape
- make sure that interpret shape function does not throw error

Optimizations

---

README.md
tfcoreml/_layers.py
tfcoreml/_layers_common.py
tfcoreml/_shape_sensitive_layers.py

Strided slice: add support for slice along H,W axis

---

README.md
tfcoreml/_layers.py
tfcoreml/_ops_to_layers.py

I added a few lines which added functionality for the tensorflow op 'Abs'.

Added tensorflow op 'Abs'

---

examples/custom_layer_examples.ipynb
examples/inception_v1_preprocessing_steps.ipynb
examples/inception_v3.ipynb
examples/linear_mnist_example.ipynb
examples/linear_mnist_train.py
examples/ssd_example.ipynb
examples/style_transfer_example.ipynb

For ipython notebook examples: 
1. Modified print commands 
2. Version specific usage of either urllib or urllib.request

Added python3 compatibility for notebook examples

---

tfcoreml/_interpret_shapes.py
tfcoreml/_shape_sensitive_layers.py

Interpret shape function can take a long time to finish

---

.gitignore
tfcoreml/_layers.py
tfcoreml/_layers_common.py

Fix in fusing bias with matmul

---

tests/test_pretrained_models.py
tfcoreml/_layers.py
tfcoreml/_tf_coreml_converter.py

- Added support for QuantizedConv2D op
TODO: quantized MatMul (inner product op) and add op level quantization tests

WIP: Add support for uint8 linear quantization

---

tfcoreml/_layers.py

Fix #210
This corrects previous incorrect fix and has been tested. It worked as long as two dimensions are being swapped. However, a three way permute involving no swapping does not work, and so will result in an assert False. This may be a bug in coreml itself.

Fix bug, transpose function not working (2)

---

tests/test_pretrained_models.py
tests/test_tf_converter.py
tfcoreml/_layers.py
tfcoreml/_tf_coreml_converter.py

Also:
- optimize the computation of all constants in the graph
- infer input shape automatically if only the first dimension is unknown

Update resize bilinear function

---

README.md
tests/test_tf_converter.py
tests/test_tf_keras_layers.py
tfcoreml/_layers.py
tfcoreml/_layers_common.py
tfcoreml/_ops_to_layers.py
tfcoreml/_shape_sensitive_layers.py
tfcoreml/_tf_coreml_converter.py

Convert with quantized convolution weights if they originate from 'Dequantize' op.

Fix for dequantize op

---

README.md
setup.py
tfcoreml/_tf_coreml_converter.py

Add CoreML 3 hook and update readme, bump version to 0.4b1

Add CoreML 3 hook and update readme, bump version to 0.4b1

---

contributing.md

modified contributing.md for tf-coreml

contributing.md

---

tfcoreml/_tf_graph_transform.py

Handle a corner case with size output size 0

---

tests/test_pretrained_models.py
tfcoreml/_tf_coreml_converter.py

Relies on https://github.com/apple/coremltools/pull/609

Allow callers to specify the input image format as NCHW or NHWC.
